#* ===================================================================
# CONFIG.YML V1.0 - VETZ.CARE HUB DIGITAL
# Tradução técnica do Dossiê Estratégico.
# ===================================================================

# --- Conexão e Configurações Base ---
backend:
  name: git-gateway
  branch: main

media_folder: "imagens/uploads"
public_folder: "/imagens/uploads"

locale: 'pt'
publish_mode: editorial_workflow

# ===================================================================
# COLEÇÕES DE CONTEÚDO (O Painel de Comando da Clínica)
# ===================================================================
collections:
  # --- 1. CONFIGURAÇÕES GLOBAIS (O "RG" DA CLÍNICA) ---
  - name: "settings"
    label: "⚙️ Configurações Gerais da Clínica"
    files:
      - label: "Informações Principais (para Google e Rodapé)"
        name: "dados_clinica"
        file: "_data/clinica.yml"
        fields:
          - { label: "Nome Oficial da Clínica", name: "nome", widget: "string", default: "VetZ.Care" }
          - { label: "Slogan", name: "slogan", widget: "string", default: "A saúde do seu pet, nossa maior expertise." }
          - { label: "Morada Completa", name: "morada", widget: "string", default: "rua 5, chacara 122, lote 17, loja 2 cep 72006060" }
          - { label: "Telefone Principal", name: "telefone", widget: "string", default: "61991659880" }
          - { label: "Email de Contato", name: "email", widget: "string", default: "planobioblogpost@gmail.com" }
          - { label: "WhatsApp Business", name: "whatsapp", widget: "string", default: "61991659880" }

  # --- 2. GESTÃO DO CORPO CLÍNICO (O MOTOR DO E-E-A-T) ---
  - name: "especialistas"
    label: "🩺 Corpo Clínico"
    label_singular: "Novo Especialista"
    folder: "_especialistas"
    create: true
    fields:
      - { label: "Nome Completo e Título", name: "title", widget: "string", hint: "Ex: Dra. Ana Sofia Mendes" }
      - { label: "CRMV", name: "crmv", widget: "string" }
      - { label: "Foto de Perfil", name: "foto", widget: "image" }
      - { label: "Especialidades", name: "especialidades", widget: "list", hint: "Adicione as áreas de foco, ex: Dermatologia, Cardiologia" }
      - { label: "Biografia Profissional", name: "bio", widget: "markdown" }

  # --- 3. SERVIÇOS CLÍNICOS (O FUNIL DE VENDAS) ---
  - name: "servicos"
    label: "💉 Serviços Clínicos"
    label_singular: "Novo Serviço"
    folder: "_servicos"
    create: true
    fields:
      - { label: "Nome do Serviço", name: "title", widget: "string", hint: "Ex: Check-up Geriátrico Canino" }
      - { label: "Descrição Completa", name: "body", widget: "markdown", hint: "Detalhe o que é o serviço, para quem é indicado e quais os benefícios." }
      - { label: "Imagem ou Ícone do Serviço", name: "image", widget: "image" }
      - { label: "Call-to-Action para WhatsApp", name: "cta_whatsapp", widget: "string", default: "Agendar este serviço via WhatsApp", hint: "Texto do botão que iniciará a conversa." }

  # --- 4. PRODUTOS DA LOJA (O PET SHOP) ---
  - name: "produtos"
    label: "🛍️ Produtos da Loja"
    label_singular: "Novo Produto"
    folder: "_produtos"
    create: true
    fields:
      - { label: "Nome do Produto", name: "title", widget: "string" }
      - { label: "Categoria", name: "categoria", widget: "select", options: ["Cães", "Gatos"] }
      - { label: "Imagem do Produto", name: "image", widget: "image" }
      - { label: "Descrição Curta", name: "summary", widget: "text" }
      - { label: "Descrição Completa", name: "body", widget: "markdown", required: false }

  # --- 5. CONTEÚDO DE AUTORIDADE (O ÍMÃ DE TRÁFEGO) ---
  - name: "artigos"
    label: "📚 Artigos e Guias (Blog)"
    label_singular: "Novo Artigo"
    folder: "_artigos"
    create: true
    fields:
      - { label: "Título do Artigo", name: "title", widget: "string" }
      - { label: "Autor", name: "autor", widget: "relation", collection: "especialistas", search_fields: ["title"], value_field: "title" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - { label: "Conteúdo do Artigo", name: "body", widget: "markdown" }
